services:
  # basic example with Dockerfile
  caddy:
    container_name: test-caddy
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      #- ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

  # basic example
  #  caddy:
  #    image: caddy:alpine
  #    restart: unless-stopped
  #    ports:
  #      - "80:80"
  #      - "443:443"
  #      - "443:443/udp"
  #    volumes:
  #      - ./Caddyfile:/etc/caddy/Caddyfile
  #      - ./site:/srv
  #      - caddy_data:/data
  #      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
